version: '3.8'

services:
## Operations Service ##
  snippet_operations_db:
    image: postgres:15.2
    container_name: snippet_operations_db
    env_file:
      - env/operations/operationsdb.env
    ports:
      - "5432:5432"
    volumes:
      - operations_db_data:/var/lib/postgresql/data
  snippet_operations:
    image: snippetoperations-app:latest
    container_name: snippet_operations
    env_file:
      - env/operations/operations.env
    ports:
      - "8080:8080"
    depends_on:
      - snippet_operations_db
## Permission Service ##
  snippet_permission_db:
    image: postgres:15.2
    container_name: snippet_permission_db
    env_file:
      - env/permission/permissiondb.env
    ports:
      - "5433:5433"
    volumes:
      - permission_db_data:/var/lib/postgresql/data

  snippet_permission:
    image: snippetpermission-app:latest
    container_name: snippet_permission
    env_file:
      - env/permission/permission.env
    ports:
      - "8081:8081"
    depends_on:
      - snippet_permission_db
## Runner Service ##
  snippet_runner_db:
    image: postgres:15.2
    container_name: snippet_runner_db
    env_file:
      - env/runner/runnerdb.env
    ports:
      - "5434:5434"
    volumes:
      - runner_db_data:/var/lib/postgresql/data

  snippet_runner:
    image: snippetrunner-app:latest
    container_name: snippet_runner
    env_file:
      - env/runner/runner.env
    ports:
      - "8082:8082"
    depends_on:
      - snippet_runner_db

volumes:
  operations_db_data:
  permission_db_data:
  runner_db_data:


